# Generated by Django 5.1.2 on 2025-01-30 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='surname',
            new_name='last_name',
        ),
    ]
